### ISSUE TITLE
CT: value failed isValidValue: Infinity

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fourier-making-waves#226] opened 2022-11-07 17:41 UTC
```
fourier-making-waves : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667831155540%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
value failed isValidValue: Infinity
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (StateSchema.ts:203:8)
at checkStateObjectValid (IOType.ts:421:42)
at isStateObjectValid (IOType.ts:461:9)
at validateStateObject (IOType.ts:298:23)
at toStateObject (ReadOnlyProperty.ts:302:34)
at getData (PhetioObject.ts:484:45)
at phetioStartEvent (ReadOnlyProperty.ts:297:66)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

fourier-making-waves : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667835911181%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
value failed isValidValue: Infinity
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (StateSchema.ts:203:8)
at checkStateObjectValid (IOType.ts:421:42)
at isStateObjectValid (IOType.ts:461:9)
at validateStateObject (IOType.ts:298:23)
at toStateObject (ReadOnlyProperty.ts:302:34)
at getData (PhetioObject.ts:484:45)
at phetioStartEvent (ReadOnlyProperty.ts:297:66)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM
```

**Comment by pixelzoom** [comment] 2022-11-08 22:31
Reproduced in phetmarks with this URL:
http://localhost:8080/fourier-making-waves/fourier-making-waves_en.html?ea&brand=phet-io&phetioStandalone&fuzz

But I can't identify what is causing this failure from the stack trace.

**Comment by samreid** [comment] 2022-11-09 16:49
@marlitas and I fixed it in the commit, by using `InfiniteNumberIO` which @zepumph introduced in https://github.com/phetsims/tandem/issues/280.  Closing.

**Closed by samreid** 2022-11-09 16:49 UTC
Labels: dev:phet-io, type:automated-testing

**Comment by zepumph** [comment] 2022-11-09 17:12
Ha! I was just typing this up. Amazing. Thanks for the find. Looks like I forgot to bring that other issue to you to review.
