### ISSUE TITLE
CT: Perennial task failed: ... false is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fourier-making-waves#24] opened 2020-12-11 16:36 UTC
```
fourier-making-waves : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (fourier-making-waves, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4381ms
>> Production minification complete: 26702ms (1424780 bytes)
>> Debug minification complete: 0ms (5568807 bytes)
Building brand: phet-io
>> Webpack build complete: 3289ms
>> Production minification complete: 21188ms (1437407 bytes)
>> Debug minification complete: 20640ms (1710097 bytes)
>> No client guides found at ../phet-io-client-guides/fourier-making-waves/, no guides being built.
Message from sim: The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
Fatal error: Perennial task failed: Error: TypeError: false is not a function
at http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:1123528
at p (http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:1123755)
at http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:1124611
at V.link (http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:39751)
at f (http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:1124594)
at new hT (http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:1124647)
at new ET (http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:1129900)
at qT.name [as createView] (http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:1132109)
at qT.initializeView (http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:778978)
at Array.<anonymous> (http://localhost:46059/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:807:951920)

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Snapshot from 12/10/2020, 7:16:09 PM
```

**Comment by pixelzoom** [comment] 2020-12-11 17:39
Reproduced locally with `grunt --brands=phet-io`.   Looks like someone changed CT to run a phet-io build, which requires client guides.  This sim is in development, so there is no reason to expect it to have client guides.

**Comment by pixelzoom** [comment] 2020-12-11 17:58
@zepumph diagnoses this properly (thanks!), a missing `assert &&`.  Fixed in the above commit, tested locally, closing.

**Closed by pixelzoom** 2020-12-11 17:58 UTC
Labels: type:automated-testing
