### ISSUE TITLE
CT: tried to make control for a non-zero harmonic invisible

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fourier-making-waves#62] opened 2021-05-20 15:28 UTC
```
fourier-making-waves : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/phet-io-wrappers/mirror-inputs/?sim=fourier-making-waves&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621503006428%22%2C%22timestamp%22%3A1621506156712%7D
Uncaught Error: Uncaught Error: Assertion failed: programming error, tried to the control for a non-zero harmonic invisible
Error: Assertion failed: programming error, tried to the control for a non-zero harmonic invisible
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/assert/js/assert.js:25:13)
at updateAmplitudeControlsVisibility (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/fourier-making-waves/js/waveGame/view/WaveGameAmplitudesChartNode.js:45:19)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/axon/js/Property.js:269:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/axon/js/Property.js:319:47
at NumberProperty.setValueAndRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/axon/js/NumberProperty.js:218:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/fourier-making-waves/js/waveGame/model/WaveGameLevel.js:104:46
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/axon/js/Property.js:269:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621503006428/axon/js/Property.js:184:14)
id: Bayes Chrome
Snapshot from 5/20/2021, 3:30:06 AM
```

**Comment by pixelzoom** [comment] 2021-05-20 15:29
Definitely related to work that I did yesterday for the Wave Game screen.

**Comment by pixelzoom** [comment] 2021-05-20 15:55
I've only been able to reproduce this on Level 5.  Just keep pressing the Refresh button and it will fail.

**Comment by pixelzoom** [comment] 2021-05-20 16:04
The problem is in WaveGameAmplitudesChartNode.js.  In this callback:

```js
    // When the challenge changes, adjust visibility of amplitude controls.
    challengeProperty.link( challenge => {
      const nonZeroHarmonics = challenge.getNonZeroHarmonics();
      const zeroHarmonics = challenge.getZeroHarmonics();
      harmonics = [ ...nonZeroHarmonics, ...dotRandom.shuffle( zeroHarmonics ) ];
      updateAmplitudeControlsVisibility( numberOfAmplitudeControlsProperty.value );
    } );
```

`updateAmplitudeControlsVisibility` is being called before `numberOfAmplitudeControlsProperty` has been updated. That's handled in WaveGameChallenge.js.

**Comment by pixelzoom** [comment] 2021-05-21 17:04
This problem would likely go away if I switched to the implementation approach described in https://github.com/phetsims/fourier-making-waves/issues/66.

**Comment by pixelzoom** [comment] 2021-05-24 23:09
This is no longer failing after addressing #66.  But it's still an ordering issue.

**Comment by pixelzoom** [comment] 2021-05-26 12:40
Still failing:

```
fourier-making-waves : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1622024049104%22%2C%22timestamp%22%3A1622026623526%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: programming error, tried to make the control for a non-zero harmonic invisible, numberOfAmplitudeControls=2 i=5 harmonic=7 amplitude=0.7
Error: Assertion failed: programming error, tried to make the control for a non-zero harmonic invisible, numberOfAmplitudeControls=2 i=5 harmonic=7 amplitude=0.7
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/assert/js/assert.js:25:13)
at updateAmplitudeControlsVisibility (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/fourier-making-waves/js/waveGame/view/WaveGameAmplitudesChartNode.js:50:19)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/axon/js/Property.js:270:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/axon/js/Property.js:320:47
at NumberProperty.setValueAndRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/axon/js/NumberProperty.js:218:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/fourier-making-waves/js/waveGame/model/WaveGameLevel.js:185:46
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/axon/js/Property.js:270:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622024049104/axon/js/Property.js:185:14)
id: Bayes Chrome
Snapshot from 5/26/2021, 4:14:09 AM
```

**Comment by pixelzoom** [comment] 2021-05-26 19:11
I ended up deleting this assertion, because it's not really necessary.   And there are 2 Properties involved that both potentially change when the challenge changes, so there's going to be an intermediate state. 

Closing.

**Closed by pixelzoom** 2021-05-26 19:11 UTC
Labels: type:automated-testing
